### ISSUE TITLE
snapshot removal

### ISSUE THREAD

**Issue by Wijnand** [Wijnand/retcon-web#3]
Snapshots should be removed automatically too.
This is on hold untill Cyso runs a less buggy opensolaris version.

**Comment by tjebbe** [comment]
We're planning to add a fresh MD1000 disk cabinet end of next week. Creating a ZFS pool without dedup should solve the problem with removing snapshots. At least so the openolaris developers claim.

**Comment by Wijnand** [comment]
Awesome!
I think I start working on it this weekend.

**Comment by tjebbe** [comment]
New MD1000 arrived today, 14 empy 1Tb disks are waiting for retcon ;) :
      16. c8t15d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      17. c8t16d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      18. c8t17d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      19. c8t18d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      20. c8t19d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      21. c8t20d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      22. c8t21d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      23. c8t22d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      24. c8t23d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      25. c8t24d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      26. c8t25d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      27. c8t26d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      28. c8t27d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>
      29. c8t28d0 <DEFAULT cyl 60765 alt 2 hd 255 sec 126>

I think we need to make a backup2 pool. Configure retcon to backup servers to the new pool and after a few weeks destroy the old pool.

**Comment by Wijnand** [comment]
In production now
